#ifndef CANSAT_MAIN_SYSTEM_RP_PICO_PICO_SDK_SENSOR_PROCESSING_S_HPP_
#define CANSAT_MAIN_SYSTEM_RP_PICO_PICO_SDK_SENSOR_PROCESSING_S_HPP_

#include "exception_handring_s.hpp"

class SensorProcessing : public Exception
{

};

#endif  // CANSAT_MAIN_SYSTEM_RP_PICO_PICO_SDK_SENSOR_PROCESSING_S_HPP_